### PR TITLE
Codebase overhaul, documentation changes

### PR DESCRIPTION
**Pull request by labsvisual**
Hey, @MeetChopra! This is an awesome concept; [Postmark](https://postmarkapp.com) offers something very similar but sadly it's not free. So, kudos there! 

---

## Changes
I have overhauled the entire code base and this change brings with it some great augmentations to the core library:
  - an Object-based and a singleton approach is now possible;
  - full access to the raw response payload as well as the parsed JSON structure is available;
  - a standard utility function maps the error codes returned by the API to more descriptive texts;
  - the entire library now has some _cool_ tests 😎 

I agree it's a bit of over-engineering for a wrapper around a simple `GET` request, but well, the API is amazing and so should the library. 

## Disambiguation
While going through the documentation, I noticed two particularly confusing responses:

  - `Invalid Email`; and
  - `Email Not Exists` [sic]

By `Invalid Email`, do you mean that the email address provided does not conform to [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt)? And by `Not Exists` do you mean that any email sent to that address will bounce? If so, I **strongly** suggest that you mention this in the API documentation. 

## API Issues
Further, I recently signed up for the API and the auth token I received was invalid for some reason. Can you look into this? I tried with two different email accounts, I guess. 

---

Best of luck!

### CODE REVIEW

**Comment by labsvisual** [comment]
@MeetChopra, the problem still persists.

**Comment by MeetChopra** [comment]
Hey! can you mail me your token at meethcopra37@gmail.com?

**Comment by labsvisual** [comment]
@MeetChopra, sent! :)

**Comment by MeetChopra** [comment]
Really Sorry, entered the wrong email address. it's meetchopra37@gmail.com

**Comment by labsvisual** [comment]
Guessed as much! 😆 Don't worry, I thought you "misplaced" the "h".

**Comment by MeetChopra** [comment]
yeah 😅

**Pull request merged**
